name: Cross-platform Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install raylib on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential libraylib-dev

      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          choco install mingw
          choco install make

      - name: Set up environment variables (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "CC=gcc" >> $GITHUB_ENV

      - name: Build project
        run: make
